db_e_skeleton:
    container_name: db_e_skeleton
    image: sameersbn/mysql
    volumes:
        - ./infra/data:/var/lib/mysql
    environment:
        - DB_NAME=demoDb
        - DB_USER=demoUser
        - DB_PASS=demoPass
    ports:
        - "33060:3306"
php_e_skeleton:
    build: .
    dockerfile: ./devops/php-fpm/Dockerfile
    environment:
      XDEBUG_CONFIG: "remote_host=10.38.101.13"
      PHP_IDE_CONFIG: "serverName=skeleton"
    container_name: php_e_skeleton
    ports:
      - '9000:9000'
    volumes:
      - ./skeleton:/var/www/e_skeleton
      - ./devops/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./Docs:/var/www/Docs
    links:
      - db_e_skeleton
web_e_skeleton:
    container_name: web_e_skeleton
    image: nginx:latest
    links:
        - db_e_skeleton
        - php_e_skeleton
    ports:
        - "8080:80"
    volumes:
        - ./skeleton:/var/www/e_skeleton
        - ./devops/nginx/default.conf:/etc/nginx/conf.d/default.conf
